title: CRTC Scraper
tagline: 
email: 
description: 
baseurl: /crtc-scraper
url: https://telecom-research.github.io/crtc-scraper
# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /crtc-scraper/:title.html
 

# Set encoding to UTF-8
encoding: utf-8

# Markdown specs
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false